name: grafana

volumes:
  data:

services:
  grafana:
    image: bitnami/grafana:$GRAFANA_VERSION
    volumes:
      - data:/opt/bitnami
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: always