global:
  resolve_timeout: 2m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 3600s
  receiver: 'alert-notifications'

receivers:
- name: 'alert-notifications' # Define the email receiver
  email_configs:
    - to: 'to email'
      from: 'from email'
      smarthost: 'smtp.example.com:587'
      auth_username: 'add user'
      auth_password: 'adding auth'
      send_resolved: true
