global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
- ./alertrules.yml
- ./conf/rules/alert.rules

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
- job_name: prometheuss
  static_configs:
  - targets:
    - prometheus:9090

- job_name: node-exporter
  static_configs:
  - targets:
    - node_exporter:9100

- job_name: Docker Job
  static_configs:
  - targets:
    - "ip-address":9323

