version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "7080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ~/jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

  agent:
    image: jenkins/ssh-agent:jdk17
    container_name: agent
    user: root
    ports:
      - "22:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY= <add your key>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - jenkins

networks:
  jenkins:
    external: true